kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ include "anki-sync-server.fullname" . }}-data'
  labels:
    app: {{ include "anki-sync-server.name" . }}
    chart: {{ include "anki-sync-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
