apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "anki-sync-server.fullname" . }}-credentials'
  labels:
    app: {{ include "anki-sync-server.name" . }}
    chart: {{ include "anki-sync-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  anki-username: {{ .Values.anki.user | b64enc | quote }}
  anki-password: {{ .Values.anki.password | b64enc | quote }}
