# Default values for anki-sync-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

anki:
  user: ""
  password: ""

image:
  repository: reg.lan.terhaak.de/jojo/anki-sync-server
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""
replicaCount: 1

## persistence for sync data
persistence:
  accessMode: ReadWriteOnce
  size: 500Mi

## http exposure
service:
  type: NodePort
  port: 27701
  
securityContext:
  ## the data file's owner group
  supplementalGroups: [5000] 

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

